theme: jekyll-theme-hacker
title: Pro Tools for Amazon QuickSight - Screenshot Chrome Extension
description: Using Pro Tools for Amazon QuickSight extension, we can export dashboard visuals (charts, graphs, or pivot tables) to images (jpg/png files). Also, supports custom capture of the Div element in the AWS QuickSight.
